# Generated by Django 3.1.5 on 2021-03-11 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_type', models.CharField(choices=[('Factory', 'Factory'), ('Dealership', 'Dealership'), ('Client', 'Client')], max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('carowner_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='management.carowner')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Factories',
            },
            bases=('management.carowner',),
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(choices=[('SEDAN', 'Sedan'), ('COUPE', 'Coupe'), ('VAN', 'Van'), ('SUV', 'Suv')], default='sedan', max_length=255)),
                ('type', models.CharField(choices=[('S', 'S'), ('L', 'L'), ('M', 'M')], default='M', max_length=255)),
                ('color', models.CharField(choices=[('White', 'White'), ('Black', 'Black'), ('Red', 'Red'), ('Blue', 'Blue')], default='white', max_length=255)),
                ('produced', models.DateField()),
                ('vin', models.CharField(max_length=25)),
                ('car_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.carowner')),
            ],
        ),
        migrations.CreateModel(
            name='Dealership',
            fields=[
                ('carowner_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='management.carowner')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('factory', models.ManyToManyField(to='management.Factory')),
            ],
            bases=('management.carowner',),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('carowner_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='management.carowner')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('dealerships', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.dealership')),
            ],
            bases=('management.carowner',),
        ),
    ]
